name: Convert Jupyter Notebook to HTML

on:
  push:
    paths:
      - '**.ipynb'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert jupyter
        pip install -r requirements.txt

    - name: Execute and convert notebooks to HTML
      run: |
        find . -iname "*.ipynb" -type f | while read -r notebook; do
          python .github/workflows/execute_and_convert.py "${notebook}" html
        done

    - name: Upload HTML files as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: html-files
        path: '*.html'

